### PR TITLE
Lab1

### PR DESCRIPTION
**Pull request by VArtem**
Just "lab1-perceptron" at the moment, more coming soon.
Update (2013.11.28): lab2(svm) and lab4(logistic) also done.

### CODE REVIEW

**Comment by danilchenko-andrey** [comment]
Лабораторная по рекомендательным системам принята

**Comment by anton-bannykh** [comment]
1 ok

**Comment by anton-bannykh** [comment]
2 ok

**Comment by anton-bannykh** [comment]
4 ok

**Pull request merged**
